/-
Copyright (c) 2026 Lars Warren Ericson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import Mathlib.Data.Set.Basic
import Mathlib.Order.BoundedOrder.Basic
import Mathlib.Order.Lattice

universe u

/-!
# Challenge — Course 21-329
-/

namespace Course21329

variable {B : Type u} [Lattice B] [BoundedOrder B]

/-- A filter on a bounded lattice `B` is a non-empty, upward-closed set closed under meets. -/
class IsFilter (F : Set B) : Prop where
  mem_top : ⊤ ∈ F
  upward : ∀ ⦃x y : B⦄, x ∈ F → x ≤ y → y ∈ F
  inf_closed : ∀ ⦃x y : B⦄, x ∈ F → y ∈ F → x ⊓ y ∈ F

/-- A filter is proper if it does not contain the bottom element `⊥`. -/
class IsProperFilter (F : Set B) : Prop extends IsFilter F where
  not_bot : ⊥ ∉ F

/-- An ultrafilter is a maximal proper filter under subset inclusion. -/
class IsUltrafilter (U : Set B) : Prop extends IsProperFilter U where
  maximal : ∀ ⦃F : Set B⦄, IsProperFilter F → U ⊆ F → U = F

/-- (a) Ultrafilter Extension Theorem. -/
theorem ultrafilter_extension (F₀ : Set B) (hF₀ : IsProperFilter F₀) :
    ∃ U : Set B, IsUltrafilter U ∧ F₀ ⊆ U := by
  sorry

/-- The principal filter generated by `⊤`. -/
def topFilter : Set B := {⊤}

/-- (b) If `⊥ ≠ ⊤`, the set of ultrafilters is non-empty. -/
theorem stoneSpace_nonempty (h_nontriv : (⊥ : B) ≠ ⊤) :
    ∃ U : Set B, IsUltrafilter U := by
  sorry

end Course21329
