import Mathlib.Order.Zorn
import BSinMeasurementTheory.Course21329.UltrafilterExtension

universe u

namespace Course21329

variable {B : Type u} [Lattice B] [BoundedOrder B]

/-- The principal filter generated by `⊤`. -/
def topFilter : Set B := {⊤}

lemma topFilter_isProperFilter (h_nontriv : (⊥ : B) ≠ ⊤) :
    IsProperFilter (topFilter (B := B)) where
  mem_top := Set.mem_singleton ⊤
  upward := by
    intro x y hx hxy
    rw [topFilter, Set.mem_singleton_iff] at hx ⊢
    subst hx
    exact top_le_iff.mp hxy
  inf_closed := by
    intro x y hx hy
    rw [topFilter, Set.mem_singleton_iff] at hx hy ⊢
    subst hx; subst hy
    rw [inf_idem]
  not_bot := by
    intro hbot
    rw [topFilter, Set.mem_singleton_iff] at hbot
    exact h_nontriv hbot

/-- (b) If `⊥ ≠ ⊤` (which holds in any infinite Boolean algebra),
the set of ultrafilters is non-empty. -/
theorem stoneSpace_nonempty (h_nontriv : (⊥ : B) ≠ ⊤) :
    ∃ U : Set B, IsUltrafilter U := by
  rcases ultrafilter_extension (topFilter (B := B)) (topFilter_isProperFilter h_nontriv) with ⟨U, hU, _⟩
  exact ⟨U, hU⟩

end Course21329
