import Mathlib.Order.Zorn
import Mathlib.SetTheory.Cardinal.Basic
import Mathlib.SetTheory.Cardinal.Arithmetic

universe u

namespace Course21329

section FilterExtension

variable {B : Type u} [Lattice B] [BoundedOrder B]

/-- A filter on a bounded lattice `B` is a non-empty, upward-closed set closed under meets. -/
def IsFilter (F : Set B) : Prop :=
  ⊤ ∈ F ∧
  (∀ ⦃x y : B⦄, x ∈ F → x ≤ y → y ∈ F) ∧
  (∀ ⦃x y : B⦄, x ∈ F → y ∈ F → x ⊓ y ∈ F)

/-- A filter is proper if it does not contain the bottom element `⊥`. -/
def IsProperFilter (F : Set B) : Prop :=
  IsFilter F ∧ ⊥ ∉ F

/-- An ultrafilter is a maximal proper filter under subset inclusion. -/
def IsUltrafilter (U : Set B) : Prop :=
  IsProperFilter U ∧ ∀ ⦃F : Set B⦄, IsProperFilter F → U ⊆ F → U = F

/-- Union of a non-empty chain of proper filters is a proper filter. -/
lemma sUnion_chain_isProperFilter (c : Set (Set B))
    (hc_sub : ∀ F ∈ c, IsProperFilter F)
    (hc_chain : IsChain (· ⊆ ·) c)
    (hc_ne : c.Nonempty) :
    IsProperFilter (⋃₀ c) := by
  refine ⟨⟨?_, ?_, ?_⟩, ?_⟩
  -- 1. ⊤ ∈ ⋃₀ c
  · rcases hc_ne with ⟨F, hF⟩
    exact Set.mem_sUnion_of_mem (hc_sub F hF).1.1 hF
  -- 2. Upward closed
  · intro x y hx hxy
    rcases Set.mem_sUnion.mp hx with ⟨F, hF, hxF⟩
    exact Set.mem_sUnion_of_mem ((hc_sub F hF).1.2.1 hxF hxy) hF
  -- 3. Closed under infima (meets)
  · intro x y hx hy
    rcases Set.mem_sUnion.mp hx with ⟨F, hF, hxF⟩
    rcases Set.mem_sUnion.mp hy with ⟨G, hG, hyG⟩
    rcases hc_chain.total hF hG with hle | hle
    · exact Set.mem_sUnion_of_mem ((hc_sub G hG).1.2.2 (hle hxF) hyG) hG
    · exact Set.mem_sUnion_of_mem ((hc_sub F hF).1.2.2 hxF (hle hyG)) hF
  -- 4. ⊥ ∉ ⋃₀ c (Properness)
  · intro hbot
    rcases Set.mem_sUnion.mp hbot with ⟨F, hF, hbotF⟩
    exact (hc_sub F hF).2 hbotF

/-- (a) Ultrafilter Extension Theorem:
Every proper filter `F₀` extends to an ultrafilter `U` using Zorn's Lemma. -/
theorem ultrafilter_extension (F₀ : Set B) (hF₀ : IsProperFilter F₀) :
    ∃ U : Set B, IsUltrafilter U ∧ F₀ ⊆ U := by
  let S := {F : Set B | IsProperFilter F ∧ F₀ ⊆ F}
  have hzorn : ∀ c ⊆ S, IsChain (· ⊆ ·) c → c.Nonempty → ∃ ub ∈ S, ∀ s ∈ c, s ⊆ ub := by
    intro c hcS hcchain hcne
    refine ⟨⋃₀ c, ⟨?_, ?_⟩, fun s hs => Set.subset_sUnion_of_mem hs⟩
    · apply sUnion_chain_isProperFilter c (fun F hF => (hcS hF).1) hcchain hcne
    · rcases hcne with ⟨F, hF⟩
      exact (hcS hF).2.trans (Set.subset_sUnion_of_mem hF)
  rcases zorn_subset_nonempty S hzorn F₀ ⟨hF₀, Set.Subset.refl F₀⟩ with ⟨U, hF₀U, hUmax⟩
  refine ⟨U, ⟨hUmax.1.1, ?_⟩, hF₀U⟩
  intro G hGprop hUG
  have hGS : G ∈ S := ⟨hGprop, hF₀U.trans hUG⟩
  exact Set.Subset.antisymm hUG (hUmax.2 hGS hUG)

/-- The principal filter generated by `⊤`. -/
def topFilter : Set B := {⊤}

lemma topFilter_isProperFilter (h_nontriv : (⊥ : B) ≠ ⊤) :
    IsProperFilter (topFilter (B := B)) := by
  refine ⟨⟨?_, ?_, ?_⟩, ?_⟩
  · exact Set.mem_singleton ⊤
  · intro x y hx hxy
    rw [topFilter, Set.mem_singleton_iff] at hx ⊢
    subst hx
    exact top_le_iff.mp hxy
  · intro x y hx hy
    rw [topFilter, Set.mem_singleton_iff] at hx hy ⊢
    subst hx; subst hy
    rw [inf_idem]
  · intro hbot
    rw [topFilter, Set.mem_singleton_iff] at hbot
    exact h_nontriv hbot

/-- (b) If `⊥ ≠ ⊤` (which holds in any infinite Boolean algebra),
the set of ultrafilters is non-empty. -/
theorem stoneSpace_nonempty (h_nontriv : (⊥ : B) ≠ ⊤) :
    ∃ U : Set B, IsUltrafilter U := by
  rcases ultrafilter_extension (topFilter (B := B)) (topFilter_isProperFilter h_nontriv) with ⟨U, hU, _⟩
  exact ⟨U, hU⟩

end FilterExtension

section CardinalArithmetic

open Cardinal

/-- (c) Cardinal-arithmetic argument:
If `|B| = ℵ₀` and `2^ℵ₀ ≤ |S(B)| ≤ 2^|B|`, then `|S(B)| = 2^ℵ₀`. -/
theorem ultrafilter_cardinality {S_B : Type*} (card_B : Cardinal)
    (hB : card_B = aleph0)
    (h_upper : #S_B ≤ 2 ^ card_B)
    (h_lower : 2 ^ aleph0 ≤ #S_B) :
    #S_B = 2 ^ aleph0 := by
  rw [hB] at h_upper
  exact le_antisymm h_upper h_lower

end CardinalArithmetic


end Course21329
